# Generated by Django 4.1.3 on 2022-12-08 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_created=True, db_index=True, default=datetime.datetime(2022, 12, 8, 17, 23, 5, 713452)),
            preserve_default=False,
        ),
    ]
