# Generated by Django 4.1.3 on 2022-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/news/cover_images'),
        ),
    ]
