# Generated by Django 4.1.3 on 2022-12-12 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_newsinteraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsinteraction',
            unique_together={('user', 'news')},
        ),
    ]
