# Generated by Django 4.1.3 on 2022-12-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsinteraction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_draft',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
