# Generated by Django 4.1.3 on 2022-12-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_relevantnews'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsinteraction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='self', to='news.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/self/cover_images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='self', to='news.tag'),
        ),
    ]
