# Generated by Django 4.1.3 on 2022-12-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_alter_newsinteraction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
