# Generated by Django 4.1.3 on 2022-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_discordwebhookstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordwebhookstore',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='discordwebhookstore',
            name='webhook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
